# -*- coding: utf-8 -*-
"""Copy_of_association_apriori.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gtPGuQcYHyJ6Y1i_8rhlnq6VwzC1tJUZ
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

dataset = pd.read_csv('/content/drive/MyDrive/Market_Basket_Optimisation.csv', header = None)
transactions = []
for i in range(0, 7501):
  transactions.append([str(dataset.values[i,j]) for j in range(0, 20)])

dataset

transactions

!pip install apyori

from apyori import apriori
rules = apriori(transactions = transactions, min_support = 0.003, min_confidence = 0.2)

results = list(rules)

results