# -*- coding: utf-8 -*-
"""Copy_of_Data_pre_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XRjRi12GL86SD0qcRA7J0nLrf2VCSlwj
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataset = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Data.csv")

from google.colab import drive
drive.mount('/content/drive')

x= dataset.iloc[:,:-1].values
y= dataset.iloc[:,-1].values
print(y)
print(x)

print(dataset)

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])

print(x)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x = np.array(ct.fit_transform(x))

print(x)