# -*- coding: utf-8 -*-
"""Diabetes EDA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KcgpYoYoaetW39M9sLaGmvHjAvpLsGfG
"""

import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

dataset = pd.read_csv("/content/drive/MyDrive/diabetes.csv")

dataset.head()

dataset.tail()

dataset.info()

dataset['Pregnancies'].describe()

dataset.describe()

dataset.isnull().sum()

plt.scatter(dataset['Pregnancies'],dataset['DiabetesPedigreeFunction'], color='red')
plt.title("Scatter Plot")
plt.xlabel("Pregnancies")
plt.ylabel("DiabetesPedigreeFunction")
plt.show()

plt.hist(dataset['DiabetesPedigreeFunction'], bins=40)
plt.title("Histogram")
plt.xlabel("DiabetesPedigreeFunction")
plt.ylabel("Frequency")
plt.show()

plt.hist(dataset['Insulin'], bins=15)
plt.title("Histogram")
plt.xlabel("Insulin")
plt.ylabel("Frequency")
plt.show()

plt.hist(dataset['BMI'], bins='auto')
plt.title("Histogram")
plt.xlabel("BMI")
plt.ylabel("Frequency")
plt.show()

sb.boxplot(x="DiabetesPedigreeFunction", data=dataset)
plt.title("Box Plot")

import scipy.stats as stats

stats.probplot(dataset['DiabetesPedigreeFunction'], dist="norm", plot=plt)
plt.title("Q-Q Plot of DiabetesPedigreeFunction Width (Normal Distribution)")
plt.grid(True)
plt.show()

import scipy.stats as stats

stats.probplot(dataset['DiabetesPedigreeFunction'], dist="uniform", plot=plt)
plt.title("Q-Q Plot of DiabetesPedigreeFunction (Uniform Distribution)")
plt.grid(True)
plt.show()